Description: [bugfix] building error with Windows+ROCm5.7+Cmake
Bug Description:
    function LOG defined in common/log.h  used in ngram-cache.cpp possibly cause the building error on Windows Platform
        Building CXX object common/CMakeFiles/common.dir/ngram-cache.cpp.obj
        FAILED: common/CMakeFiles/common.dir/ngram-cache.cpp.obj
        llama/llama.cpp/common/./log.h:469:5: error: expected ')'

    function fprintf used in common/ngram-cache.cpp may cause the same error

Solve Method:
    remove the including of log.h in ngram-cache.cpp
    remove the function call LOG in ngram-cache.cpp
    remove the function call fprintf in ngram-cache.cpp

Changes to be committed:
    modified:   common/ngram-cache.cpp