Fix broken build for LLAMA_METAL
a113689 broke the build with:

```
llama.cpp:1828:50: error: use of undeclared identifier 'cur'
        ggml_metal_get_tensor   (lctx.ctx_metal, cur);
```

This commit removes the stray line to repair the build.